apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-deployment
  namespace: sleep-app
  labels:
    app: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        # Just spin & wait forever
        command: [ "/bin/bash", "-c", "--" ]
        args:
        - |
          cntr=0
          while true; do
              cntr=$((cntr+1))
              timestamp=`date --utc +"%Y-%m-%d %H:%M:%SZ"`
              echo "[$timestamp] $cntr"
              sleep 10
          done
